### ISSUE TITLE
Tenants

### ISSUE THREAD

**Issue by yaxarat** [vcu-cmsc355-f17/android-app-triumph#5]

**Comment by ranama2** [comment]
As a tenant (user),
So that I can use the app,
I want to be able to see too each users' due balance.
-------------------[Scenario 1]-------------------
Feature: User can click a button to which navigates to tenant info page
Scenario: Tenant page
Steps:

Given that I am on the home page.
When I press the tenant button.
Then I should be able to go to the tenant page.
Then I should be able to see all the users and their due balance.
-------------------[Scenario 2]-------------------
Feature: User can go back to the home page
Scenario: Home page
Steps:

Given that I am on the tenant page.
When I press the home button.
Then I should be able to go back to the home page.
-------------------[Scenario 3]-------------------
Feature: User can see history my previous activity.
Scenario: History
Steps:

Given that I am on the tenant page.
When I press the history button.
Then I should be able to see my completed transactions.
Then I should be able to see my pending transactions.
